### ISSUE TITLE
A false positive reentrancy vulnerability in contract spank_chain_payment

### ISSUE THREAD

**Issue by nicedinner** [smartbugs/smartbugs-curated#10]
code: 
function LCOpenTimeout(bytes32 _lcID) public {
         require(msg.sender == Channels[_lcID].partyAddresses[0] && Channels[_lcID].isOpen == false);
         require(now > Channels[_lcID].LCopenTimeout);

         if(Channels[_lcID].initialDeposit[0] != 0) {
             // <yes> <report> REENTRANCY   //Line 426
             Channels[_lcID].partyAddresses[0].transfer(Channels[_lcID].ethBalances[0]);
         }
         if(Channels[_lcID].initialDeposit[1] != 0) {
             // <yes> <report> REENTRANCY  //Line 430
             require(Channels[_lcID].token.transfer(Channels[_lcID].partyAddresses[0], Channels[_lcID].erc20Balances[0]),"CreateChannel: token transfer failure");
         }

         emit DidLCClose(_lcID, 0, Channels[_lcID].ethBalances[0], Channels[_lcID].erc20Balances[0], 0, 0);

         // only safe to delete since no action was taken on this channel
         delete Channels[_lcID];
     }

The code at Line 426 use "transfer" to send  ether. Therefore, the gas can be used for this call set to 2300. This amount of gas cannot trigger reentrancy.

**Comment by gsalzer** [comment]
Thanks for reporting your observation. I have to check with the original authors how to interpret their annotations. If it is intended as "the reentrancy vulnerability consists in line 426 AND 430", then they may be correct. If they wanted to express that there are two vulnerabilities, then you are right: line 426 in itself cannot give rise to a reentrancy attack, because of the limited gas.

If I were to attack the contract, I'd use `createChannel` to write the address of an attacker contract into `Channels[_lcID].token`, then call it via line 430 and call from there repeatedly `LCOpenTimeout` to extract Ether using line 426. In this sense, both calls contribute to the success of the attack

**Comment by nicedinner** [comment]
Thanks for explain how to attack the contract. You are correct.

**Comment by tdurieux** [comment]
If you want more information, the original victim of this attack wrote a blog post: https://medium.com/spankchain/we-got-spanked-what-we-know-so-far-d5ed3a0f38fe
